command: motd
motd:
  - "&a&m+&8&m                                              &a&m+&f"
  - "Welcome to &a&lLorem&fIpsum"
  - ""
  - "New to &a&lLorem&fIpsum? Type [&a/faq](run_command=/faq hover=&fRun the &a/faq&f command)&f to get started!"
  - "Type [&a/help](run_command=/help hover=&fRun the &a/help&f command)&f for a list of available commands."
  - "&a&m+&8&m                                              &a&m+&f"
